name: scale-nginx
description: nginx [engine x] is an HTTP and reverse proxy server, a mail proxy server, and a generic TCP/UDP proxy server.
annotations:
  title: nginx
type: application
version: 1.0.0
apiVersion: v2
appVersion: 8.13.4
kubeVersion: '>=1.16.0-0'
maintainers:
  - name: IAmHafid
    url: https://github.com/IAmHafid
    email: atlas-develop@proton.me
dependencies:
  #- name: common
   # repository: file://../../../common
    #version: 1.2.9
home: https://github.com/IAmHafid/truescale/tree/main/incubator/scale-nginx
icon: https://github.com/IAmHafid/truescale/tree/main/incubator/scale-nginx/icon.png
sources:
  - https://hub.docker.com/_/nginx
keywords:
  - nginx
  - server
  - http