image:
  repository: https://github.com/nginxinc/docker-nginx
  pullPolicy: IfNotPresent
  tag: 1.25.4

resources:
  limits:
    cpu: 4000m
    memory: 4Gi

  # esConfig:
  #   password: ''
  #  heapSize: 512m
  #  nodeName: elastic_search_node
  #  additionalEnvs: []

# Not user configurable
esRunAs:
  user: 1000
  group: 1000

  # esNetwork:
  #  httpPort: 30003
  #  hostNetwork: false
  #  certificateID:

esStorage:
  data:
    type: ixVolume
    ixVolumeConfig:
      datasetName: data
  additionalStorages: []